# Generated by Django 5.1.4 on 2024-12-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcategory_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraph_intro', models.TextField()),
                ('paragraph_body', models.TextField(blank=True, null=True)),
                ('paragraph_end', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(default='uncategorized'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
