# Generated by Django 5.1.3 on 2024-11-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
