# Generated by Django 5.1.4 on 2024-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutme_postcategory_slug_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(),
        ),
    ]
