# Generated by Django 5.1.4 on 2024-12-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postcategory_name_alter_postcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='Uncategorized', max_length=255, null=True),
        ),
    ]
